from tkinter import *
from winsound import *
from random import randint
import time

fen = Tk()
fen.title("Le quiz économique de la zone euro de Harlequin")

compteur=0

canvas = Canvas(fen, width=600, height=400, background='gold')

txt = canvas.create_text(300, 280, text="DONNEZ UN PRIX ENTRE 0 ET 2000 MON CHER", font="Impact 20", fill="green")
txtrecommencer = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")

photo = PhotoImage(file="baguette.gif") #0.95
photo2 = PhotoImage(file="birman.gif")  #914
photo3 = PhotoImage(file="caddie.gif")  #119
photo4 = PhotoImage(file="diable.gif")  #999
photo5 = PhotoImage(file="doritos.gif") #7.24
photo6 = PhotoImage(file="kebab.gif")   #1172
photo7 = PhotoImage(file="palmier.gif") #66.95
photo8 = PhotoImage(file="rsa.gif")     #0
photo9 = PhotoImage(file="ukulele.gif") #196,33
photo10 = PhotoImage(file="zelda.gif")  #33.99
photofaux = PhotoImage(file="harlequin.gif")
photomaitre = PhotoImage(file='harlequin.gif')

image = canvas.create_image(75, 0, anchor=NW, image=photo)


def bonnereponse():
    canvas.delete('all')
    imagemaitre = canvas.create_image(100, 0, anchor=NW, image=photomaitre)
    txt2 = canvas.create_text(300, 350, text='      Bon, maintenant que tu sais jouer, \n on va pouvoir démarrer le grand quiz ! \n                                Es-tu prêt ?', font='Impact 20', fill='green')
    boutonOui1 = Button(fen, text='OUI !', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=oui)
    boutonOui2 = Button(fen, text='OUI !', font='Impact 40', bd=1, bg='gold', activebackground='magenta', command=oui)
    BtCanOui1 = canvas.create_window(125, 200, window=boutonOui1)
    BtCanOui2 = canvas.create_window(475, 200, window=boutonOui2)
def oui():
    musique3 = PlaySound("DEBUT.wav", SND_FILENAME | SND_ASYNC)
    time.sleep(6.2)
    canvas.delete('all')
    txtrecommencer2 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    musique = PlaySound("Musique de G@mer.wav", SND_LOOP | SND_ASYNC)
    image2 = canvas.create_image(200, 0, anchor=NW, image=photo2)
    boutonBirman1 = Button(fen, text='404€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtBirman1 = canvas.create_window(125, 350, window=boutonBirman1)
    boutonBirman2 = Button(fen, text='914€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai)
    BtBirman2 = canvas.create_window(475, 350, window=boutonBirman2)
def faux():
    global compteur
    canvas.delete('all')
    compteur = compteur + 1
    musique2 = PlaySound("TU AS PERDU.wav", SND_FILENAME | SND_ASYNC)
    imagefaux = canvas.create_image(100, 75, anchor=NW, image=photofaux)
    txtfaux = canvas.create_text(300, 200, text='TU AS PERDU HIHI', font='Impact 20', fill='green')
    boutonRecommencer = Button(fen, text='Recommencer !', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=recommencer)
    BtReco = canvas.create_window(300, 300, window=boutonRecommencer)
def recommencer():
    canvas.delete('all')
    txtrecommencerreco = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    txtreco = canvas.create_text(300, 280, text="DONNEZ UN PRIX ENTRE 0 ET 2000 MON CHER", font="Impact 20", fill="green")
    imagereco = canvas.create_image(75, 0, anchor=NW, image=photo)
    boutonReco = Button(fen, text='0.95€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=bonnereponse)
    BtReco = canvas.create_window(300, 350, window=boutonbaguette)
def vrai():
    canvas.delete('all')
    txtrecommencer3 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    image3 = canvas.create_image(160, 0, anchor=NW, image=photo3)
    boutonCaddie1 = Button(fen, text='99€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtCaddie1 = canvas.create_window(125, 350, window=boutonCaddie1)
    boutonCaddie2 = Button(fen, text='119€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai2)
    BtCaddie2 = canvas.create_window(300, 350, window=boutonCaddie2)
    boutonCaddie3 = Button(fen, text='109€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtCaddie3 = canvas.create_window(475, 350, window=boutonCaddie3)
def vrai2():
    canvas.delete('all')
    txtrecommencer4 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    image4 = canvas.create_image(160, 5, anchor=NW, image=photo4)
    boutonDiable1 = Button(fen, text='€999', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai3)
    BtDiable1 = canvas.create_window(75, 350, window=boutonDiable1)
    boutonDiable2 = Button(fen, text='999€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtDiable2 = canvas.create_window(225, 350, window=boutonDiable2)
    boutonDiable3 = Button(fen, text='666€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtDiable3 = canvas.create_window(375, 350, window=boutonDiable3)
    boutonDiable4 = Button(fen, text='€666', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtDiable4 = canvas.create_window(525, 350, window=boutonDiable4)
def vrai3():
    canvas.delete('all')
    txtrecommencer5 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    image5 = canvas.create_image(160, 0, anchor=NW, image=photo5)
    boutonDoritos1 = Button(fen, text='1,99€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtDoritos1 = canvas.create_window(75, 350, window=boutonDoritos1)
    boutonDoritos2 = Button(fen, text='3,50€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtDoritos2 = canvas.create_window(188, 350, window=boutonDoritos2)
    boutonDoritos3 = Button(fen, text='8,48€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtDoritos3 = canvas.create_window(300, 350, window=boutonDoritos3)
    boutonDoritos4 = Button(fen, text='6,99€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtDoritos4 = canvas.create_window(413, 350, window=boutonDoritos4)
    boutonDoritos5 = Button(fen, text='7,24€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai4)
    BtDoritos5 = canvas.create_window(525, 350, window=boutonDoritos5)
def vrai4():
    canvas.delete('all')
    image6 = canvas.create_image(75, 0, anchor=NW, image=photo6)
    txtrecommencer6 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    boutonKebab1 = Button(fen, text='9.50€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtKebab1 = canvas.create_window(150, 290, window=boutonKebab1)
    boutonKebab2 = Button(fen, text='13€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtKebab2 = canvas.create_window(300, 290, window=boutonKebab2)
    boutonKebab3 = Button(fen, text='1999€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtKebab3 = canvas.create_window(450, 290, window=boutonKebab3)
    boutonKebab4 = Button(fen, text='564€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtKebab4 = canvas.create_window(150, 350, window=boutonKebab4)
    boutonKebab5 = Button(fen, text='1172€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai5)
    BtKebab5 = canvas.create_window(300, 350, window=boutonKebab5)
    boutonKebab6 = Button(fen, text='4.72€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtKebab6 = canvas.create_window(450, 350, window=boutonKebab6)
def vrai5():
    canvas.delete('all')
    txtrecommencer7 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    image7 = canvas.create_image(200, 0, anchor=NW, image=photo7)
    boutonPalmier1 = Button(fen, text='152€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtPalmier1 = canvas.create_window(150, 290, window=boutonPalmier1)
    boutonPalmier2 = Button(fen, text='99.99€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtPalmier2 = canvas.create_window(300, 290, window=boutonPalmier2)
    boutonPalmier3 = Button(fen, text='66.95€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai6)
    BtPalmier3 = canvas.create_window(450, 290, window=boutonPalmier3)
    boutonPalmier4 = Button(fen, text='69€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtPalmier4 = canvas.create_window(150, 350, window=boutonPalmier4)
    boutonPalmier5 = Button(fen, text='4.50€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtPalmier5 = canvas.create_window(300, 350, window=boutonPalmier5)
    boutonPalmier6 = Button(fen, text='59.99€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtPalmier6 = canvas.create_window(450, 350, window=boutonPalmier6)
def vrai6():
    canvas.delete('all')
    txtrecommencer8 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    image8 = canvas.create_image(150, 0, anchor=NW, image=photo8)
    boutonRSA1 = Button(fen, text='Moins cher que gratuit', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=vrai7)
    BtRSA1 = canvas.create_window(150, 290, window=boutonRSA1)
    boutonRSA2 = Button(fen, text='État€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtRSA2 = canvas.create_window(300, 290, window=boutonRSA2)
    boutonRSA3 = Button(fen, text='700€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtRSA3 = canvas.create_window(450, 290, window=boutonRSA3)
    boutonRSA4 = Button(fen, text='0€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai7)
    BtRSA4 = canvas.create_window(150, 350, window=boutonRSA4)
    boutonRSA5 = Button(fen, text='Pôle emploi€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtRSA5 = canvas.create_window(300, 350, window=boutonRSA5)
    boutonRSA6 = Button(fen, text='Bonne réponse', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtRSA6 = canvas.create_window(450, 350, window=boutonRSA6)
def vrai7():
    canvas.delete('all')
    txtrecommencer9 = canvas.create_text(525, 50, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    image9 = canvas.create_image(200, 0, anchor=NW, image=photo9)
    boutonUku1 = Button(fen, text='196,33€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=vrai8)
    BtUku1 = canvas.create_window(150, 290, window=boutonUku1)
    boutonUku2 = Button(fen, text='99€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtUku2 = canvas.create_window(300, 290, window=boutonUku2)
    boutonUku3 = Button(fen, text='129€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtUku3 = canvas.create_window(450, 290, window=boutonUku3)
    boutonUku4 = Button(fen, text='78€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtUku4 = canvas.create_window(150, 350, window=boutonUku4)
    boutonUku5 = Button(fen, text='250€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtUku5 = canvas.create_window(300, 350, window=boutonUku5)
    boutonUku6 = Button(fen, text='196,33$', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtUku6 = canvas.create_window(450, 350, window=boutonUku6)
def vrai8():
    canvas.delete('all')
    txtrecommencer10 = canvas.create_text(300, 20, text=("Morts : " + str(compteur)), font="Impact 18", fill="black")
    txtboss = canvas.create_text(300, 360, text="BOSS FINAL", font="Impact 20", fill="green")
    image10 = canvas.create_image(200, 50, anchor=NW, image=photo10)
    boutonZelda1 = Button(fen, text='99€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda1 = canvas.create_window(60, 40, window=boutonZelda1)
    boutonZelda2 = Button(fen, text='129€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda2 = canvas.create_window(60, 100, window=boutonZelda2)
    boutonZelda3 = Button(fen, text='49€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda3 = canvas.create_window(60, 160, window=boutonZelda3)
    boutonZelda4 = Button(fen, text='39€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda4 = canvas.create_window(60, 220, window=boutonZelda4)
    boutonZelda5 = Button(fen, text='55€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda5 = canvas.create_window(60, 280, window=boutonZelda5)
    boutonZelda6 = Button(fen, text='22€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda7 = canvas.create_window(60, 340, window=boutonZelda6)
    boutonZelda7 = Button(fen, text='199€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda8 = canvas.create_window(120, 40, window=boutonZelda7)
    boutonZelda8 = Button(fen, text='47€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda8 = canvas.create_window(120, 100, window=boutonZelda8)
    boutonZelda9 = Button(fen, text='35€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda9 = canvas.create_window(120, 160, window=boutonZelda9)
    boutonZelda10 = Button(fen, text='24€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda10 = canvas.create_window(120, 220, window=boutonZelda10)
    boutonZelda11 = Button(fen, text='25€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda11 = canvas.create_window(120, 280, window=boutonZelda11)
    boutonZelda12 = Button(fen, text='34$', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda12 = canvas.create_window(120, 340, window=boutonZelda12)
    boutonZelda13 = Button(fen, text='69€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda13 = canvas.create_window(450, 40, window=boutonZelda13)
    boutonZelda14 = Button(fen, text='63€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda14 = canvas.create_window(450, 100, window=boutonZelda14)
    boutonZelda15 = Button(fen, text='28€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda15 = canvas.create_window(450, 160, window=boutonZelda15)
    boutonZelda16 = Button(fen, text='33€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda16 = canvas.create_window(450, 220, window=boutonZelda16)
    boutonZelda17 = Button(fen, text='1€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda17 = canvas.create_window(450, 280, window=boutonZelda17)
    boutonZelda18 = Button(fen, text='34€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=gg)
    BtZelda18 = canvas.create_window(450, 340, window=boutonZelda18)
    boutonZelda19 = Button(fen, text='3€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda19 = canvas.create_window(510, 40, window=boutonZelda19)
    boutonZelda20 = Button(fen, text='18€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda20 = canvas.create_window(510, 100, window=boutonZelda20)
    boutonZelda21 = Button(fen, text='19€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda21 = canvas.create_window(510, 160, window=boutonZelda21)
    boutonZelda22 = Button(fen, text='8€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda22 = canvas.create_window(510, 220, window=boutonZelda22)
    boutonZelda23 = Button(fen, text='1999€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda23 = canvas.create_window(510, 280, window=boutonZelda23)
    boutonZelda24 = Button(fen, text='999€', font='Impact 15', bd=1, bg='gold', activebackground='magenta', command=faux)
    BtZelda24 = canvas.create_window(510, 340, window=boutonZelda24)
def gg():
    canvas.delete('all')
    son4 = PlaySound("FIN.wav", SND_FILENAME | SND_ASYNC)
    imagefin = canvas.create_image(110, 0, anchor=NW, image=photomaitre)
    txt340000000 = canvas.create_text(300, 330, text="               Ainsi donc, tu m'as vaincu... \n Je t'avais donc bien sous-estimé, Luigi...", font="Impact 17", fill="green")
    boutonQuitter = Button(fen, text='Quitter le jeu', font='Impact 10', bd=1, bg='gold', activebackground='magenta', command=quit)
    BtQuitter = canvas.create_window(300, 380, window=boutonQuitter)
    boutonRecommencer = Button(fen, text='Recommencer !', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=recommencer)
    BtReco = canvas.create_window(300, 90, window=boutonRecommencer)

boutonbaguette = Button(fen, text='0.95€', font='Impact 20', bd=1, bg='gold', activebackground='magenta', command=bonnereponse)
btBaguette_fen = canvas.create_window(300, 350, window=boutonbaguette)             
canvas.pack()

print (compteur)

fen.mainloop()
